import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import Nav from "@/components/NAV"
import Provider from "@/context/provider"
import { Session } from "next-auth";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session,
}: Readonly<{
  children: React.ReactNode;
  session: Session|null;
}>) {
  return (
    <html lang="en">
      <Provider session={session}>
      <body className={inter.className}>
        <Nav/>
        {children}
      </body>
      </Provider>
    </html>
  );
}
